version: "3.8"

services:

  main:
    depends_on:
      - db
    container_name: "${SERVER_NAME}"
    build: ./
    env_file: ./.env
    ports:
      - "${SERVER_PORT}:8082"

  db:
    container_name: "${POSTGRES_NAME}"
    image: postgres
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_NAME}
    ports:
      - "5432:5432"