spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://${POSTGRES_NAME}:${PSQL_PORT}/${PSQL_NAME}
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: ${SERVER_PORT}

springdoc:
  swagger-ui:
    path: /api.html

jwt:
  secret-word: ${JWT_SECRET}
  refresh-token-lifetime: ${REFRESH_TOKEN_LIFE_TIME}
  access-token-lifetime:  ${ACCESS_TOKEN_LIFE_TIME}

minio:
  url: http://${MINIO_NAME}:${MINIO_CONSOLE_PORT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
