spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost/blps
    username: blps
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
  base-url: http://localhost:8080/

springdoc:
  swagger-ui:
    path: /api.html


jwt:
  secret-word: "WHAT_IF_ITS_JUST_A_DREAM"
  refresh-token-lifetime: 86400000
  access-token-lifetime:  3600000

minio:
  url: http://localhost:9000
  access-key: root
  secret-key: rootroot

mail:
  username: no-reply@plofin.com
  password: q99mrvNi0EQFa4iza2tD
  confirmation_hash_lifetime: 3600000
logging:
  level:
    com.project.debby : DEBUG
